# Generated by Django 3.0.4 on 2020-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('paiment_due', models.DateField()),
                ('client', models.CharField(max_length=100)),
            ],
        ),
    ]
