# Generated by Django 3.0.4 on 2020-04-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ethapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Service', models.CharField(default='Electricy', max_length=100)),
                ('Num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_Provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ethapp1.paymentParty'),
            preserve_default=False,
        ),
    ]
